
version: '3'

# Define services
services:

  # App Service
  quest-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    restart: unless-stopped
    environment: 
      SECRET_WORD: illusion
